# -- Main Menu -- (Top Navigation Bar)

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 5

[[main]]
  name = "News"
  pageRef = "/news"
  weight = 10

[[main]]
  name = "Samsung"
  pageRef = "/samsung"
  weight = 20

[[main]]
  name = "Apple"
  pageRef = "/apple"
  weight = 30

[[main]]
  name = "Android"
  pageRef = "/android"
  weight = 40

[[main]]
  name = "Games"
  pageRef = "/games"
  weight = 50

[[main]]
  name = "AI"
  pageRef = "/ai"
  weight = 60

[[main]]
  name = "Reviews"
  pageRef = "/reviews"
  weight = 70

[[main]]
  name = "About Us"
  pageRef = "/about"
  weight = 80

[[main]]
  name = "Contact Us"
  pageRef = "/contact"
  weight = 90

# -- Footer Menu --

[[footer]]
  name = "Privacy Policy"
  pageRef = "/privacy-policy"
  weight = 10

[[footer]]
  name = "Terms and Conditions"
  pageRef = "/terms"
  weight = 20

[[footer]]
  name = "Disclaimer"
  pageRef = "/disclaimer"
  weight = 30
